# Generated by Django 5.1.7 on 2025-04-06 03:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_userprofile_instagram_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(db_index=True, max_length=255)),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("views", models.BigIntegerField(default=0)),
                ("subscribers", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["channel_id", "date"],
                        name="dashboard_c_channel_3777d6_idx",
                    )
                ],
                "unique_together": {("channel_id", "date")},
            },
        ),
    ]
