# Generated by Django 5.1.7 on 2025-04-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_analytics_access",
            field=models.BooleanField(default=False),
        ),
    ]
