# Generated by Django 5.1.7 on 2025-04-07 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_userprofile_has_analytics_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="connected_users",
            field=models.ManyToManyField(
                blank=True, related_name="connected_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
