# Generated by Django 5.1.7 on 2025-04-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_userprofile_connected_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "video_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("channel_id", models.CharField(db_index=True, max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.BigIntegerField(default=0)),
                ("like_count", models.BigIntegerField(default=0)),
                ("comment_count", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-published_at"],
            },
        ),
    ]
